import = ["/home/elusive/.config/alacritty/moonfly.toml"]

[env]
TERM = "xterm-256color"

[shell]
program = "/usr/bin/zsh"
args = ["--login", "-c", "tmux attach || tmux"]
# wsl
# program = "C:\\Windows\\System32\\wsl.exe"
# args = ["--cd ~", "tmux attach || tmux"]

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { family = "Hack Nerd Font", style = "Bold" }
bold_italic = { family = "Hack Nerd Font", style = "Bold Italic" }
italic = { family = "Hack Nerd Font", style = "Italic" }
